/*
  Copyright (c) 2015, Alcatel-Lucent Inc
  All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are met:
      * Redistributions of source code must retain the above copyright
        notice, this list of conditions and the following disclaimer.
      * Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.
      * Neither the name of the copyright holder nor the names of its contributors
        may be used to endorse or promote products derived from this software without
        specific prior written permission.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
  DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

@import <Foundation/Foundation.j>
@import <AppKit/CPArrayController.j>
@import <Bambou/NURESTObject.j>

@import "Fetchers/NUMetadatasFetcher.j"
@import "Fetchers/NUGlobalMetadatasFetcher.j"

NUJobAssocEntityType_ACLENTRY_LOCATION = @"ACLENTRY_LOCATION";
NUJobAssocEntityType_ADDRESS_RANGE = @"ADDRESS_RANGE";
NUJobAssocEntityType_ADDRESS_RANGE_STATE = @"ADDRESS_RANGE_STATE";
NUJobAssocEntityType_ALARM = @"ALARM";
NUJobAssocEntityType_APPD_APPLICATION = @"APPD_APPLICATION";
NUJobAssocEntityType_APPD_EXTERNAL_APP_SERVICE = @"APPD_EXTERNAL_APP_SERVICE";
NUJobAssocEntityType_APPD_FLOW = @"APPD_FLOW";
NUJobAssocEntityType_APPD_FLOW_FORWARDING_POLICY = @"APPD_FLOW_FORWARDING_POLICY";
NUJobAssocEntityType_APPD_FLOW_SECURITY_POLICY = @"APPD_FLOW_SECURITY_POLICY";
NUJobAssocEntityType_APPD_SERVICE = @"APPD_SERVICE";
NUJobAssocEntityType_APPD_TIER = @"APPD_TIER";
NUJobAssocEntityType_APPLICATION = @"APPLICATION";
NUJobAssocEntityType_AUTO_DISC_GATEWAY = @"AUTO_DISC_GATEWAY";
NUJobAssocEntityType_BACK_HAUL_SERVICE_RESP = @"BACK_HAUL_SERVICE_RESP";
NUJobAssocEntityType_BGPPEER = @"BGPPEER";
NUJobAssocEntityType_BGP_DAMPENING_MED_RESPONSE = @"BGP_DAMPENING_MED_RESPONSE";
NUJobAssocEntityType_BGP_NEIGHBOR = @"BGP_NEIGHBOR";
NUJobAssocEntityType_BGP_NEIGHBOR_MED_RESPONSE = @"BGP_NEIGHBOR_MED_RESPONSE";
NUJobAssocEntityType_BGP_PROFILE = @"BGP_PROFILE";
NUJobAssocEntityType_BGP_PROFILE_MED_RESPONSE = @"BGP_PROFILE_MED_RESPONSE";
NUJobAssocEntityType_BOOTSTRAP = @"BOOTSTRAP";
NUJobAssocEntityType_BOOTSTRAP_ACTIVATION = @"BOOTSTRAP_ACTIVATION";
NUJobAssocEntityType_BRIDGEINTERFACE = @"BRIDGEINTERFACE";
NUJobAssocEntityType_CERTIFICATE = @"CERTIFICATE";
NUJobAssocEntityType_CHILD_ENTITY_POLICY_CHANGE = @"CHILD_ENTITY_POLICY_CHANGE";
NUJobAssocEntityType_CLOUD_MGMT_SYSTEM = @"CLOUD_MGMT_SYSTEM";
NUJobAssocEntityType_CONTAINER_RESYNC = @"CONTAINER_RESYNC";
NUJobAssocEntityType_CUSTOMER_VRF_SEQUENCENO = @"CUSTOMER_VRF_SEQUENCENO";
NUJobAssocEntityType_DC_CONFIG = @"DC_CONFIG";
NUJobAssocEntityType_DHCP_ALLOC_MESSAGE = @"DHCP_ALLOC_MESSAGE";
NUJobAssocEntityType_DHCP_CONFIG_RESP = @"DHCP_CONFIG_RESP";
NUJobAssocEntityType_DHCP_OPTION = @"DHCP_OPTION";
NUJobAssocEntityType_DISKSTATS = @"DISKSTATS";
NUJobAssocEntityType_DOMAIN = @"DOMAIN";
NUJobAssocEntityType_DOMAIN_CONFIG = @"DOMAIN_CONFIG";
NUJobAssocEntityType_DOMAIN_CONFIG_RESP = @"DOMAIN_CONFIG_RESP";
NUJobAssocEntityType_DOMAIN_FLOATING_IP_ACL_TEMPLATE = @"DOMAIN_FLOATING_IP_ACL_TEMPLATE";
NUJobAssocEntityType_DOMAIN_FLOATING_IP_ACL_TEMPLATE_ENTRY = @"DOMAIN_FLOATING_IP_ACL_TEMPLATE_ENTRY";
NUJobAssocEntityType_DOMAIN_TEMPLATE = @"DOMAIN_TEMPLATE";
NUJobAssocEntityType_DSCP_FORWARDING_CLASS_MAPPING = @"DSCP_FORWARDING_CLASS_MAPPING";
NUJobAssocEntityType_DSCP_FORWARDING_CLASS_TABLE = @"DSCP_FORWARDING_CLASS_TABLE";
NUJobAssocEntityType_EGRESS_ACL = @"EGRESS_ACL";
NUJobAssocEntityType_EGRESS_ACL_ENTRY = @"EGRESS_ACL_ENTRY";
NUJobAssocEntityType_EGRESS_ACL_TEMPLATE = @"EGRESS_ACL_TEMPLATE";
NUJobAssocEntityType_EGRESS_ACL_TEMPLATE_ENTRY = @"EGRESS_ACL_TEMPLATE_ENTRY";
NUJobAssocEntityType_EGRESS_QOS_MR = @"EGRESS_QOS_MR";
NUJobAssocEntityType_EGRESS_QOS_PRIMITIVE = @"EGRESS_QOS_PRIMITIVE";
NUJobAssocEntityType_EGRESS_QOS_QUEUE_MR = @"EGRESS_QOS_QUEUE_MR";
NUJobAssocEntityType_ENDPOINT = @"ENDPOINT";
NUJobAssocEntityType_ENTERPRISE = @"ENTERPRISE";
NUJobAssocEntityType_ENTERPRISE_CONFIG = @"ENTERPRISE_CONFIG";
NUJobAssocEntityType_ENTERPRISE_CONFIG_RESP = @"ENTERPRISE_CONFIG_RESP";
NUJobAssocEntityType_ENTERPRISE_NETWORK = @"ENTERPRISE_NETWORK";
NUJobAssocEntityType_ENTERPRISE_PERMISSION = @"ENTERPRISE_PERMISSION";
NUJobAssocEntityType_ENTERPRISE_PROFILE = @"ENTERPRISE_PROFILE";
NUJobAssocEntityType_ENTERPRISE_SECURED_DATA = @"ENTERPRISE_SECURED_DATA";
NUJobAssocEntityType_ENTERPRISE_SECURITY = @"ENTERPRISE_SECURITY";
NUJobAssocEntityType_ENTITY_METADATA_BINDING = @"ENTITY_METADATA_BINDING";
NUJobAssocEntityType_ESI_SEQUENCENO = @"ESI_SEQUENCENO";
NUJobAssocEntityType_EVENT_LOG = @"EVENT_LOG";
NUJobAssocEntityType_EVPN_BGP_COMMUNITY_TAG_ENTRY = @"EVPN_BGP_COMMUNITY_TAG_ENTRY";
NUJobAssocEntityType_EVPN_BGP_COMMUNITY_TAG_SEQ_NO = @"EVPN_BGP_COMMUNITY_TAG_SEQ_NO";
NUJobAssocEntityType_EXPORTIMPORT = @"EXPORTIMPORT";
NUJobAssocEntityType_EXTERNAL_SERVICE = @"EXTERNAL_SERVICE";
NUJobAssocEntityType_FLOATINGIP = @"FLOATINGIP";
NUJobAssocEntityType_FLOATINGIP_ACL = @"FLOATINGIP_ACL";
NUJobAssocEntityType_FLOATINGIP_ACL_ENTRY = @"FLOATINGIP_ACL_ENTRY";
NUJobAssocEntityType_FLOATING_IP_ACL_TEMPLATE = @"FLOATING_IP_ACL_TEMPLATE";
NUJobAssocEntityType_FLOATING_IP_ACL_TEMPLATE_ENTRY = @"FLOATING_IP_ACL_TEMPLATE_ENTRY";
NUJobAssocEntityType_GATEWAY = @"GATEWAY";
NUJobAssocEntityType_GATEWAY_CONFIG = @"GATEWAY_CONFIG";
NUJobAssocEntityType_GATEWAY_CONFIG_RESP = @"GATEWAY_CONFIG_RESP";
NUJobAssocEntityType_GATEWAY_SECURED_DATA = @"GATEWAY_SECURED_DATA";
NUJobAssocEntityType_GATEWAY_SECURITY = @"GATEWAY_SECURITY";
NUJobAssocEntityType_GATEWAY_SECURITY_PROFILE_REQUEST = @"GATEWAY_SECURITY_PROFILE_REQUEST";
NUJobAssocEntityType_GATEWAY_SECURITY_PROFILE_RESPONSE = @"GATEWAY_SECURITY_PROFILE_RESPONSE";
NUJobAssocEntityType_GATEWAY_SECURITY_REQUEST = @"GATEWAY_SECURITY_REQUEST";
NUJobAssocEntityType_GATEWAY_SECURITY_RESPONSE = @"GATEWAY_SECURITY_RESPONSE";
NUJobAssocEntityType_GATEWAY_SERVICE_CONFIG = @"GATEWAY_SERVICE_CONFIG";
NUJobAssocEntityType_GATEWAY_SERVICE_CONFIG_RESP = @"GATEWAY_SERVICE_CONFIG_RESP";
NUJobAssocEntityType_GATEWAY_TEMPLATE = @"GATEWAY_TEMPLATE";
NUJobAssocEntityType_GATEWAY_VPORT_CONFIG = @"GATEWAY_VPORT_CONFIG";
NUJobAssocEntityType_GATEWAY_VPORT_CONFIG_RESP = @"GATEWAY_VPORT_CONFIG_RESP";
NUJobAssocEntityType_GEO_VM_EVENT = @"GEO_VM_EVENT";
NUJobAssocEntityType_GEO_VM_REQ = @"GEO_VM_REQ";
NUJobAssocEntityType_GEO_VM_RES = @"GEO_VM_RES";
NUJobAssocEntityType_GROUP = @"GROUP";
NUJobAssocEntityType_GROUPKEY_ENCRYPTION_PROFILE = @"GROUPKEY_ENCRYPTION_PROFILE";
NUJobAssocEntityType_HEALTH_REQ = @"HEALTH_REQ";
NUJobAssocEntityType_HOSTINTERFACE = @"HOSTINTERFACE";
NUJobAssocEntityType_HSC = @"HSC";
NUJobAssocEntityType_IKE_CERTIFICATE = @"IKE_CERTIFICATE";
NUJobAssocEntityType_IKE_ENCRYPTION_PROFILE = @"IKE_ENCRYPTION_PROFILE";
NUJobAssocEntityType_IKE_GATEWAY = @"IKE_GATEWAY";
NUJobAssocEntityType_IKE_GATEWAY_CONFIG = @"IKE_GATEWAY_CONFIG";
NUJobAssocEntityType_IKE_GATEWAY_CONNECTION = @"IKE_GATEWAY_CONNECTION";
NUJobAssocEntityType_IKE_GATEWAY_PROFILE = @"IKE_GATEWAY_PROFILE";
NUJobAssocEntityType_IKE_PSK = @"IKE_PSK";
NUJobAssocEntityType_IKE_SUBNET = @"IKE_SUBNET";
NUJobAssocEntityType_INFRASTRUCTURE_CONFIG = @"INFRASTRUCTURE_CONFIG";
NUJobAssocEntityType_INFRASTRUCTURE_GATEWAY_PROFILE = @"INFRASTRUCTURE_GATEWAY_PROFILE";
NUJobAssocEntityType_INFRASTRUCTURE_PORT_PROFILE = @"INFRASTRUCTURE_PORT_PROFILE";
NUJobAssocEntityType_INFRASTRUCTURE_VSC_PROFILE = @"INFRASTRUCTURE_VSC_PROFILE";
NUJobAssocEntityType_INGRESS_ACL = @"INGRESS_ACL";
NUJobAssocEntityType_INGRESS_ACL_ENTRY = @"INGRESS_ACL_ENTRY";
NUJobAssocEntityType_INGRESS_ACL_TEMPLATE = @"INGRESS_ACL_TEMPLATE";
NUJobAssocEntityType_INGRESS_ACL_TEMPLATE_ENTRY = @"INGRESS_ACL_TEMPLATE_ENTRY";
NUJobAssocEntityType_INGRESS_ADV_FWD = @"INGRESS_ADV_FWD";
NUJobAssocEntityType_INGRESS_ADV_FWD_ENTRY = @"INGRESS_ADV_FWD_ENTRY";
NUJobAssocEntityType_INGRESS_ADV_FWD_TEMPLATE = @"INGRESS_ADV_FWD_TEMPLATE";
NUJobAssocEntityType_INGRESS_ADV_FWD_TEMPLATE_ENTRY = @"INGRESS_ADV_FWD_TEMPLATE_ENTRY";
NUJobAssocEntityType_INGRESS_EXT_SERVICE = @"INGRESS_EXT_SERVICE";
NUJobAssocEntityType_INGRESS_EXT_SERVICE_ENTRY = @"INGRESS_EXT_SERVICE_ENTRY";
NUJobAssocEntityType_INGRESS_EXT_SERVICE_TEMPLATE = @"INGRESS_EXT_SERVICE_TEMPLATE";
NUJobAssocEntityType_INGRESS_EXT_SERVICE_TEMPLATE_ENTRY = @"INGRESS_EXT_SERVICE_TEMPLATE_ENTRY";
NUJobAssocEntityType_IP_BINDING = @"IP_BINDING";
NUJobAssocEntityType_JOB = @"JOB";
NUJobAssocEntityType_KEYSERVER_MEMBER = @"KEYSERVER_MEMBER";
NUJobAssocEntityType_KEYSERVER_MONITOR = @"KEYSERVER_MONITOR";
NUJobAssocEntityType_KEYSERVER_MONITOR_ENCRYPTED_SEED = @"KEYSERVER_MONITOR_ENCRYPTED_SEED";
NUJobAssocEntityType_KEYSERVER_MONITOR_SEED = @"KEYSERVER_MONITOR_SEED";
NUJobAssocEntityType_KEYSERVER_MONITOR_SEK = @"KEYSERVER_MONITOR_SEK";
NUJobAssocEntityType_KEYSERVER_NOTIFICATION = @"KEYSERVER_NOTIFICATION";
NUJobAssocEntityType_L2DOMAIN = @"L2DOMAIN";
NUJobAssocEntityType_L2DOMAIN_SHARED = @"L2DOMAIN_SHARED";
NUJobAssocEntityType_L2DOMAIN_TEMPLATE = @"L2DOMAIN_TEMPLATE";
NUJobAssocEntityType_LDAP_CONFIG = @"LDAP_CONFIG";
NUJobAssocEntityType_LIBVIRT_INTERFACE = @"LIBVIRT_INTERFACE";
NUJobAssocEntityType_LICENSE = @"LICENSE";
NUJobAssocEntityType_LOCATION = @"LOCATION";
NUJobAssocEntityType_MC_CHANNEL_MAP = @"MC_CHANNEL_MAP";
NUJobAssocEntityType_MC_LIST = @"MC_LIST";
NUJobAssocEntityType_MC_RANGE = @"MC_RANGE";
NUJobAssocEntityType_METADATA = @"METADATA";
NUJobAssocEntityType_METADATA_TAG = @"METADATA_TAG";
NUJobAssocEntityType_MIRROR_DESTINATION = @"MIRROR_DESTINATION";
NUJobAssocEntityType_MONITORING_PORT = @"MONITORING_PORT";
NUJobAssocEntityType_MULTI_NIC_VPORT = @"MULTI_NIC_VPORT";
NUJobAssocEntityType_NATMAPENTRY = @"NATMAPENTRY";
NUJobAssocEntityType_NETWORK_ELEMENT = @"NETWORK_ELEMENT";
NUJobAssocEntityType_NETWORK_LAYOUT = @"NETWORK_LAYOUT";
NUJobAssocEntityType_NETWORK_MACRO_GROUP = @"NETWORK_MACRO_GROUP";
NUJobAssocEntityType_NETWORK_POLICY_GROUP = @"NETWORK_POLICY_GROUP";
NUJobAssocEntityType_NEXT_HOP_RESP = @"NEXT_HOP_RESP";
NUJobAssocEntityType_NODE_EXECUTION_ERROR = @"NODE_EXECUTION_ERROR";
NUJobAssocEntityType_NSGATEWAY = @"NSGATEWAY";
NUJobAssocEntityType_NSGATEWAY_CONFIG = @"NSGATEWAY_CONFIG";
NUJobAssocEntityType_NSGATEWAY_TEMPLATE = @"NSGATEWAY_TEMPLATE";
NUJobAssocEntityType_NSG_NOTIFICATION = @"NSG_NOTIFICATION";
NUJobAssocEntityType_NSPORT = @"NSPORT";
NUJobAssocEntityType_NSPORT_STATIC_CONFIG = @"NSPORT_STATIC_CONFIG";
NUJobAssocEntityType_NSPORT_TEMPLATE = @"NSPORT_TEMPLATE";
NUJobAssocEntityType_NSPORT_VLAN_CONFIG = @"NSPORT_VLAN_CONFIG";
NUJobAssocEntityType_NSREDUNDANT_GW_GRP = @"NSREDUNDANT_GW_GRP";
NUJobAssocEntityType_NS_REDUNDANT_PORT = @"NS_REDUNDANT_PORT";
NUJobAssocEntityType_PATCONFIG_CONFIG_RESP = @"PATCONFIG_CONFIG_RESP";
NUJobAssocEntityType_PATNATPOOL = @"PATNATPOOL";
NUJobAssocEntityType_PERMISSION = @"PERMISSION";
NUJobAssocEntityType_PERMITTED_ACTION = @"PERMITTED_ACTION";
NUJobAssocEntityType_POLICING_POLICY = @"POLICING_POLICY";
NUJobAssocEntityType_POLICY_DECISION = @"POLICY_DECISION";
NUJobAssocEntityType_POLICY_GROUP = @"POLICY_GROUP";
NUJobAssocEntityType_POLICY_GROUP_TEMPLATE = @"POLICY_GROUP_TEMPLATE";
NUJobAssocEntityType_PORT = @"PORT";
NUJobAssocEntityType_PORT_MR = @"PORT_MR";
NUJobAssocEntityType_PORT_PUSH = @"PORT_PUSH";
NUJobAssocEntityType_PORT_TEMPLATE = @"PORT_TEMPLATE";
NUJobAssocEntityType_PORT_VLAN_CONFIG = @"PORT_VLAN_CONFIG";
NUJobAssocEntityType_PORT_VLAN_CONFIG_RESPONSE = @"PORT_VLAN_CONFIG_RESPONSE";
NUJobAssocEntityType_PUBLIC_NETWORK = @"PUBLIC_NETWORK";
NUJobAssocEntityType_QOS_PRIMITIVE = @"QOS_PRIMITIVE";
NUJobAssocEntityType_RATE_LIMITER = @"RATE_LIMITER";
NUJobAssocEntityType_RD_SEQUENCENO = @"RD_SEQUENCENO";
NUJobAssocEntityType_REDUNDANT_GW_GRP = @"REDUNDANT_GW_GRP";
NUJobAssocEntityType_ROUTING_POLICY = @"ROUTING_POLICY";
NUJobAssocEntityType_ROUTING_POL_MED_RESPONSE = @"ROUTING_POL_MED_RESPONSE";
NUJobAssocEntityType_RTRD_ENTITY = @"RTRD_ENTITY";
NUJobAssocEntityType_RTRD_SEQUENCENO = @"RTRD_SEQUENCENO";
NUJobAssocEntityType_SERVICES_GATEWAY_RESPONSE = @"SERVICES_GATEWAY_RESPONSE";
NUJobAssocEntityType_SERVICE_GATEWAY_RESPONSE = @"SERVICE_GATEWAY_RESPONSE";
NUJobAssocEntityType_SERVICE_VRF_SEQUENCENO = @"SERVICE_VRF_SEQUENCENO";
NUJobAssocEntityType_SHAPING_POLICY = @"SHAPING_POLICY";
NUJobAssocEntityType_SHARED_RESOURCE = @"SHARED_RESOURCE";
NUJobAssocEntityType_SITE = @"SITE";
NUJobAssocEntityType_SITE_REQ = @"SITE_REQ";
NUJobAssocEntityType_SITE_RES = @"SITE_RES";
NUJobAssocEntityType_STATIC_ROUTE = @"STATIC_ROUTE";
NUJobAssocEntityType_STATIC_ROUTE_RESP = @"STATIC_ROUTE_RESP";
NUJobAssocEntityType_STATISTICS = @"STATISTICS";
NUJobAssocEntityType_STATSSERVER = @"STATSSERVER";
NUJobAssocEntityType_STATS_COLLECTOR = @"STATS_COLLECTOR";
NUJobAssocEntityType_STATS_POLICY = @"STATS_POLICY";
NUJobAssocEntityType_STATS_TCA = @"STATS_TCA";
NUJobAssocEntityType_SUBNET = @"SUBNET";
NUJobAssocEntityType_SUBNET_ENTRY = @"SUBNET_ENTRY";
NUJobAssocEntityType_SUBNET_MAC_ENTRY = @"SUBNET_MAC_ENTRY";
NUJobAssocEntityType_SUBNET_POOL_ENTRY = @"SUBNET_POOL_ENTRY";
NUJobAssocEntityType_SUBNET_TEMPLATE = @"SUBNET_TEMPLATE";
NUJobAssocEntityType_SYSTEM_CONFIG = @"SYSTEM_CONFIG";
NUJobAssocEntityType_SYSTEM_CONFIG_REQ = @"SYSTEM_CONFIG_REQ";
NUJobAssocEntityType_SYSTEM_CONFIG_RESP = @"SYSTEM_CONFIG_RESP";
NUJobAssocEntityType_SYSTEM_MONITORING = @"SYSTEM_MONITORING";
NUJobAssocEntityType_UNSUPPORTED = @"UNSUPPORTED";
NUJobAssocEntityType_UPLINK_RD = @"UPLINK_RD";
NUJobAssocEntityType_USER = @"USER";
NUJobAssocEntityType_VIRTUAL_IP = @"VIRTUAL_IP";
NUJobAssocEntityType_VIRTUAL_MACHINE = @"VIRTUAL_MACHINE";
NUJobAssocEntityType_VIRTUAL_MACHINE_REPORT = @"VIRTUAL_MACHINE_REPORT";
NUJobAssocEntityType_VLAN = @"VLAN";
NUJobAssocEntityType_VLAN_CONFIG_RESPONSE = @"VLAN_CONFIG_RESPONSE";
NUJobAssocEntityType_VLAN_TEMPLATE = @"VLAN_TEMPLATE";
NUJobAssocEntityType_VMWARE_RELOAD_CONFIG = @"VMWARE_RELOAD_CONFIG";
NUJobAssocEntityType_VMWARE_VCENTER = @"VMWARE_VCENTER";
NUJobAssocEntityType_VMWARE_VCENTER_CLUSTER = @"VMWARE_VCENTER_CLUSTER";
NUJobAssocEntityType_VMWARE_VCENTER_DATACENTER = @"VMWARE_VCENTER_DATACENTER";
NUJobAssocEntityType_VMWARE_VCENTER_EAM_CONFIG = @"VMWARE_VCENTER_EAM_CONFIG";
NUJobAssocEntityType_VMWARE_VCENTER_HYPERVISOR = @"VMWARE_VCENTER_HYPERVISOR";
NUJobAssocEntityType_VMWARE_VCENTER_VRS_BASE_CONFIG = @"VMWARE_VCENTER_VRS_BASE_CONFIG";
NUJobAssocEntityType_VMWARE_VCENTER_VRS_CONFIG = @"VMWARE_VCENTER_VRS_CONFIG";
NUJobAssocEntityType_VMWARE_VRS_ADDRESS_RANGE = @"VMWARE_VRS_ADDRESS_RANGE";
NUJobAssocEntityType_VM_DESCRIPTION = @"VM_DESCRIPTION";
NUJobAssocEntityType_VM_INTERFACE = @"VM_INTERFACE";
NUJobAssocEntityType_VM_RESYNC = @"VM_RESYNC";
NUJobAssocEntityType_VNID_SEQUENCENO = @"VNID_SEQUENCENO";
NUJobAssocEntityType_VPN_CONNECT = @"VPN_CONNECT";
NUJobAssocEntityType_VPORT = @"VPORT";
NUJobAssocEntityType_VPORTTAG = @"VPORTTAG";
NUJobAssocEntityType_VPORTTAGTEMPLATE = @"VPORTTAGTEMPLATE";
NUJobAssocEntityType_VPORT_GATEWAY_RESPONSE = @"VPORT_GATEWAY_RESPONSE";
NUJobAssocEntityType_VPORT_MEDIATION_REQUEST = @"VPORT_MEDIATION_REQUEST";
NUJobAssocEntityType_VPORT_MIRROR = @"VPORT_MIRROR";
NUJobAssocEntityType_VPORT_TAG_BASE = @"VPORT_TAG_BASE";
NUJobAssocEntityType_VPRN_LABEL_SEQUENCENO = @"VPRN_LABEL_SEQUENCENO";
NUJobAssocEntityType_VRS = @"VRS";
NUJobAssocEntityType_VSC = @"VSC";
NUJobAssocEntityType_VSD = @"VSD";
NUJobAssocEntityType_VSD_COMPONENT = @"VSD_COMPONENT";
NUJobAssocEntityType_VSG_REDUNDANT_PORT = @"VSG_REDUNDANT_PORT";
NUJobAssocEntityType_VSP = @"VSP";
NUJobAssocEntityType_WAN_SERVICE = @"WAN_SERVICE";
NUJobAssocEntityType_ZONE = @"ZONE";
NUJobAssocEntityType_ZONE_TEMPLATE = @"ZONE_TEMPLATE";
NUJobCommand_APPLY_POLICY_CHANGES = @"APPLY_POLICY_CHANGES";
NUJobCommand_ASSIGN_NSG_UPGRADE_PROFILE = @"ASSIGN_NSG_UPGRADE_PROFILE";
NUJobCommand_BATCH_CRUD_REQUEST = @"BATCH_CRUD_REQUEST";
NUJobCommand_BATCH_GATEWAY_SECURED_DATAS = @"BATCH_GATEWAY_SECURED_DATAS";
NUJobCommand_BEGIN_POLICY_CHANGES = @"BEGIN_POLICY_CHANGES";
NUJobCommand_CERTIFICATE_NSG_RENEW = @"CERTIFICATE_NSG_RENEW";
NUJobCommand_CERTIFICATE_NSG_REVOKE = @"CERTIFICATE_NSG_REVOKE";
NUJobCommand_CLEAR_IPSEC_DATA = @"CLEAR_IPSEC_DATA";
NUJobCommand_CLEAR_MAC_MOVE_ALARMS = @"CLEAR_MAC_MOVE_ALARMS";
NUJobCommand_DEPLOY = @"DEPLOY";
NUJobCommand_DISCARD_POLICY_CHANGES = @"DISCARD_POLICY_CHANGES";
NUJobCommand_EXPORT = @"EXPORT";
NUJobCommand_FORCE_KEYSERVER_UPDATE = @"FORCE_KEYSERVER_UPDATE";
NUJobCommand_FORCE_KEYSERVER_UPDATE_ACK = @"FORCE_KEYSERVER_UPDATE_ACK";
NUJobCommand_FORCE_KEYSERVER_VSD_RESYNC = @"FORCE_KEYSERVER_VSD_RESYNC";
NUJobCommand_GATEWAY_AUDIT = @"GATEWAY_AUDIT";
NUJobCommand_GET_ZFB_INFO = @"GET_ZFB_INFO";
NUJobCommand_IMPORT = @"IMPORT";
NUJobCommand_KEYSERVER_NOTIFICATION_TEST = @"KEYSERVER_NOTIFICATION_TEST";
NUJobCommand_NOTIFY_NSG_REGISTRATION = @"NOTIFY_NSG_REGISTRATION";
NUJobCommand_NOTIFY_NSG_REGISTRATION_ACK = @"NOTIFY_NSG_REGISTRATION_ACK";
NUJobCommand_NOTIFY_NSG_REGISTRATION_TEST = @"NOTIFY_NSG_REGISTRATION_TEST";
NUJobCommand_NSG_NOTIFICATION_TEST = @"NSG_NOTIFICATION_TEST";
NUJobCommand_NSG_REGISTRATION_INFO = @"NSG_REGISTRATION_INFO";
NUJobCommand_REDEPLOY = @"REDEPLOY";
NUJobCommand_REJECT_ZFB_REQUEST = @"REJECT_ZFB_REQUEST";
NUJobCommand_RELOAD = @"RELOAD";
NUJobCommand_RELOAD_GEO_REDUNDANT_INFO = @"RELOAD_GEO_REDUNDANT_INFO";
NUJobCommand_RELOAD_NSG_CONFIG = @"RELOAD_NSG_CONFIG";
NUJobCommand_RESTART = @"RESTART";
NUJobCommand_RETRIEVE_ACTIVE_NSGS = @"RETRIEVE_ACTIVE_NSGS";
NUJobCommand_START = @"START";
NUJobCommand_STATUS = @"STATUS";
NUJobCommand_STOP = @"STOP";
NUJobCommand_SYNC = @"SYNC";
NUJobCommand_UNDEPLOY = @"UNDEPLOY";
NUJobCommand_VCENTER_ADD_COMPUTERESOURCE_INSCOPE = @"VCENTER_ADD_COMPUTERESOURCE_INSCOPE";
NUJobCommand_VCENTER_DELETE_AGENCY = @"VCENTER_DELETE_AGENCY";
NUJobCommand_VCENTER_MARK_AGENT_VM_AVAILABLE = @"VCENTER_MARK_AGENT_VM_AVAILABLE";
NUJobCommand_VCENTER_RECONNECT = @"VCENTER_RECONNECT";
NUJobCommand_VCENTER_RELOAD = @"VCENTER_RELOAD";
NUJobCommand_VCENTER_REMOVE_COMPUTERESOURCE_INSCOPE = @"VCENTER_REMOVE_COMPUTERESOURCE_INSCOPE";
NUJobCommand_VCENTER_SCRIPT_UPGRADE_VRS = @"VCENTER_SCRIPT_UPGRADE_VRS";
NUJobCommand_VCENTER_SYNC = @"VCENTER_SYNC";
NUJobCommand_VCENTER_UPGRADE_VRS = @"VCENTER_UPGRADE_VRS";
NUJobEntityScope_ENTERPRISE = @"ENTERPRISE";
NUJobEntityScope_GLOBAL = @"GLOBAL";
NUJobStatus_FAILED = @"FAILED";
NUJobStatus_RUNNING = @"RUNNING";
NUJobStatus_SUCCESS = @"SUCCESS";


/*!
    Represents JOB entity. The job API accepts a command and parameters and executes the job and returns the results. Jobs API are typically used for long running tasks.
*/
@implementation NUJob : NURESTObject
{
    /*!
        Additional arguments required for the specific command. Differs based on types of command.
    */
    NURESTObject _parameters @accessors(property=parameters);
    /*!
        ID of the user who last updated the object.
    */
    CPString _lastUpdatedBy @accessors(property=lastUpdatedBy);
    /*!
        Results from the execution of the job
    */
    NURESTObject _result @accessors(property=result);
    /*!
        Specify if scope of entity is Data center or Enterprise level
    */
    CPString _entityScope @accessors(property=entityScope);
    /*!
        Name of the command.
    */
    CPString _command @accessors(property=command);
    /*!
        Indicates the progress of the job as a faction. eg : 0.5 means 50% done.
    */
    CPNumber _progress @accessors(property=progress);
    /*!
        Entity with which this job is associated Refer to API section for supported types.
    */
    CPString _assocEntityType @accessors(property=assocEntityType);
    /*!
        Current status of the job. Possible values are RUNNING, FAILED, SUCCESS, .
    */
    CPString _status @accessors(property=status);
    /*!
        External object ID. Used for integration with third party systems
    */
    CPString _externalID @accessors(property=externalID);
    
    NUMetadatasFetcher _childrenMetadatas @accessors(property=childrenMetadatas);
    NUGlobalMetadatasFetcher _childrenGlobalMetadatas @accessors(property=childrenGlobalMetadatas);
    
}


#pragma mark -
#pragma mark Class Method

+ (CPString)RESTName
{
    return @"job";
}


#pragma mark -
#pragma mark Initialization

- (id)init
{
    if (self = [super init])
    {
        [self exposeLocalKeyPathToREST:@"parameters"];
        [self exposeLocalKeyPathToREST:@"lastUpdatedBy"];
        [self exposeLocalKeyPathToREST:@"result"];
        [self exposeLocalKeyPathToREST:@"entityScope"];
        [self exposeLocalKeyPathToREST:@"command"];
        [self exposeLocalKeyPathToREST:@"progress"];
        [self exposeLocalKeyPathToREST:@"assocEntityType"];
        [self exposeLocalKeyPathToREST:@"status"];
        [self exposeLocalKeyPathToREST:@"externalID"];
        
        _childrenMetadatas = [NUMetadatasFetcher fetcherWithParentObject:self];
        _childrenGlobalMetadatas = [NUGlobalMetadatasFetcher fetcherWithParentObject:self];
        
        
    }

    return self;
}

@end